services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel_network

  mysql:
    image: mysql:5.7
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        # MYSQL_USER: '${DB_USERNAME}'
        # MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
