version: '3'

services:
  app:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql

  redis:
    image: redis:latest

volumes:
  dbdata:
